<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"><head><title>Expert (async_kernel.Async_kernel.Monitor.Expert)</title><link rel="stylesheet" href="../../../../_odoc-theme/odoc.css"/><meta charset="utf-8"/><meta name="generator" content="odoc v1.1.1-1373-g2e7c1c75"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/><script src="../../../../highlight.pack.js"></script><script>hljs.initHighlightingOnLoad();</script></head><body><nav><a href="../index.html">Up</a> â€“ <a href="../../../index.html">async_kernel</a> &#x00BB; <a href="../../index.html">Async_kernel</a> &#x00BB; <a href="../index.html">Monitor</a> &#x00BB; Expert</nav><header><h1>Module <code>Monitor.Expert</code></h1></header><div class="content"><div><div class="spec value" id="val-try_with_log_exn" class="anchored"><a href="#val-try_with_log_exn" class="anchor"></a><code><span class="keyword">val</span> try_with_log_exn : <span><span>(exn <span>&#45;&gt;</span> unit)</span> <a href="../../../../core_kernel/Core_kernel/index.html#type-ref">Core_kernel.ref</a></span></code></div><div><p><code>try_with_log_exn</code> is called by <code>try_with</code> when an exception is raised to a <code>try_with</code> that already returned. <code>Async_unix</code> sets it to a function that logs.</p></div></div></div></body></html>